### ISSUE TITLE
This mod is still confusing

### ISSUE THREAD

**Issue by wqferr** [lukebemish/cobbled_paths#3]
If not for the closed issue where you explain in 2 steps how to use this mod, I would have never figured it out. This really needs a readme for yesterday, or at the very least these instructions in the CurseForge page.

**Comment by lukebemish** [comment]
I added some detail to the page

**Comment by alaestor** [comment]
Well it certainly took me a while to figure it out...

You have to right-click on an appropriate block while holding the appropriate item from this mod ('Cobbles' and the '[...] Sett' items e.g. 'Stone Sett', 'Blackstone Sett', etc. which can be made in the stonecutter).
![interactions](https://github.com/lukebemish/CobbledPaths/assets/30993312/5a2ca37e-d4d4-4154-b053-e608599a3370)

They can further be modified by using the sledge hammer for 'cracked' variants, and specific items for 'decorated' variants ([per the mod page description](https://www.curseforge.com/minecraft/mc-mods/cobbled-paths))

> Gold nuggets can be used to decorate blackstone paths; nether wart to decorate nether brick paths; and cobble to decorate cobbled paths.

However, I haven't figured out what "cobble to decorate cobbled paths" means. Using 'Cobbles' twice doesn't do anything and using regular cobblestone blocks just puts the block on top of the path (destroying the path and turning it into a regular dirt block). So idk about that one...

The spade just seems to be used for replacing certain blocks. E.g. right-clicking on dirt with the spade while holding endstone in your offhand will replace the dirt block with the sandstone one. This can't switch out existing paths; only the base block.


Also, note that unlike vanilla dirt path blocks, the resulting cobbled 'path' blocks can't be copied in creative mode or found in JEI, but they can be placed by WorldEdit under the `cobbledpaths` namespace e.g. `cobbledpaths:deepslate_path` (including cracked and decorated variants). While I love the path block, this mod can certainly be a bit of a pain in the butt. Why not just right-click with the spade like how vanilla does dirt paths? For balance reasons because these paths give a speed buff?

---

Anyways, I hope this comment helps anyone else who is as confused as I was...
