### ISSUE TITLE
1.18.2 doesn't have this groovy mod loader? How does this mod load? Exit code 1

### ISSUE THREAD

**Issue by xFirefalconx** [lukebemish/cobbled_paths#4]
You write in the cf page it needs this modloader which is not available for 1.18.2. I am debugging my pack rn and it crashes with just two mods, nobody stating what exactly you need to run it. Super bamboozled. Please clarify.

**Comment by lukebemish** [comment]
GML is only needed in 1.19+

**Comment by lukebemish** [comment]
If it is crashing please provide a log

**Comment by xFirefalconx** [comment]
Thanks for the fast reply.
Apparently because of the current situation I just drag/drop mods from one folder to another (because testing) to prevent from anything happening to the working clean mod files, I don't download anything new. 
It didn't tell me Architectury was necessary. For some reason. 
It looks like that was the issue, after I did a bit of switching back and forth it turned architectury active again and the game starts. Maybe add that this mod is necessary? Would help people like me to determine what is causing issues. I deactivated it after I deactivated another mod, so it was unavailable for your mod and hence crashed.

**Comment by lukebemish** [comment]
My mod declares a dependency on architectury, both in the mod and on the file on curseforge. If that's not working I have to assume it's that stuff is being loaded too early due to mixins, though I'm not sure even there how that could happen. There's not too much more I can do about it because the 1.18.2 versions are no longer being developed.
